###

GET http://localhost:4000/games

###

POST  http://localhost:4000/allGames
Content-Type: application/json

{
    "game_name":"Sharon",
    "author":"Kondapaturi",
    "game_image_url":"snsjsnjsnsj",
    "content":"ssnjsnsjnsjsn",
    "summary":"Naughty Dog and published by Sony Interactive Entertainment.",
    "published_date":"19/06/2393"
}

###

PUT http://localhost:4000/update/13
Content-Type: application/json

{
    "game_name":"sorry",
    "author":"ertyy",
    "game_image_url":"self",
    "content":"34eee",
    "summary":"3reevf",
    "published_date":"19/05/2393"
}

###

DELETE http://localhost:4000/deleteGame/13