###

GET http://localhost:4000/games

###

POST  http://localhost:4000/allGames
Content-Type: application/json


###

PUT http://localhost:4000/update/5
Content-Type: application/json

{
    "game_image_url":"https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQ-1JQmmFGex9il7ac1CY1E8Na5di8idOCs-VpoO5-vBCw6jbwGV95LvwxOW_6onfIsBeCIhw"
}
